### ISSUE TITLE
Make site responsive

### ISSUE THREAD

**Issue by MAGGIx1404** [MAGGIx1404/Jomato.com#1]
This site is not responsive and many sections are break at some point.

**Comment by vrajpatel9988** [comment]
I want to do this project.

**Comment by vrajpatel9988** [comment]
I am start doing your site responsive please assign me this project. I start contributing this project.

**Comment by vrajpatel9988** [comment]
I fork this repo.

**Comment by MAGGIx1404** [comment]
hmm but your work is not correctly
